### ISSUE TITLE
python3.7.1 

### ISSUE THREAD

**Issue by javaliuseu** [fbdesignpro/sweetviz#54] opened 2020-08-12 14:48 UTC
module 'sweetviz' has no attribute 'analyze'

**Comment by javaliuseu** [comment] 2020-08-12 14:50
Hi,
This is the first time that I use sweetviz, python3.7.1 
Just pip installed sweetviz and run the sample code and get the error 

import sweetviz as sv

my_report = sv.analyze(my_dataframe)
my_report.show_html() # Default arguments will generate to "SWEETVIZ_REPORT.html"

module 'sweetviz' has no attribute 'analyze'

**Comment by fbdesignpro** [comment] 2020-08-12 17:20
@javaliuseu this seems to happen on some installs for some reason. Can you tell us what happens if you simply type `sv` after the import statement? (you should get some sort of description of the module)

Also, can you tell us which environment you are using (Pycharm, Jupyter, etc.)? This would help narrow it down. Thank you!!

**Comment by javaliuseu** [comment] 2020-08-12 18:59
@fbdesignpro thank you for your prompt reply.
if I type sv it simply get " (module) sv " prompt when cursor point to it.
and if I use tab to get more functions hints I could not find any function as the documentation states.
but wired to see other variables I defined in my code.
I use vscode 1.47.2 as python dev env.

Thanks!

**Comment by fbdesignpro** [comment] 2020-08-12 23:35
@javaliuseu if you just type "sv" then ENTER, what kind of output do you get?

**Comment by javaliuseu** [comment] 2020-08-13 08:03
@fbdesignpro if I just type sv then ENTER, I got nothing but only sv itself.

Thanks!

**Comment by javaliuseu** [comment] 2020-08-13 12:19
I also tried python 3.6 and python3.8 same issue.
I am running on linux btw
3.10.0-1062.1.1.el7.x86_64 #1 SMP Tue Aug 13 18:39:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by fbdesignpro** [comment] 2021-07-08 14:14
Closing as it is old and cannot reproduce issue.

**Closed by fbdesignpro** 2021-07-08 14:14 UTC
Labels: can't repro issue, install/setup
