### ISSUE TITLE
error Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans. occure

### ISSUE THREAD

**Issue by fleschgordon** [fbdesignpro/sweetviz#61] opened 2020-09-30 15:14 UTC
hi,

sweetviz does not work for a special table

i get the following error
AAfindfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['DejaVu Sans'] not found. Falling back to DejaVu Sans.
findfont: Font family ['DejaVu Sans'] not found. Falling back to DejaVu Sans.
findfont: Font family ['DejaVu Sans'] not found. Falling back to DejaVu Sans.
findfont: Font family ['DejaVu Sans'] not found. Falling back to DejaVu Sans.
...
RecursionError: maximum recursion depth exceeded in comparison

how can i resolve this ?

thanks for any hint

**Comment by fbdesignpro** [comment] 2020-10-05 12:25
@fleschgordon I have not seen this before... the package should find the font. You mention it is for a special table. Would you have any further information on the type of data you are creating a report for, also the Python platform (e.g. PyCharm, jupyter, etc) and version (and Sweetviz version) you are using? 

Thank you!
Francois

**Comment by fbdesignpro** [comment] 2020-10-05 12:52
@fleschgordon also, can you tell me what version of matplotlib is installed? (different versions have different quirks) Thank you!

**Comment by fleschgordon** [comment] 2020-10-20 05:59
Hi @fbdesignpro  
i use python 3.6.10., matplotlib version is 3.1.3, the columns with the error is from type object (nvarchar(400) in the database).
i use sweetviz 1.0b3

**Comment by fbdesignpro** [comment] 2020-10-21 13:10
@fleschgordon thank you for the details. Sweetviz was recently updated to 1.1 and I know in some cases font issues were fixed. Can you try uninstalling then reinstalling Sweetviz and see if it fixes it?

**Comment by fleschgordon** [comment] 2020-10-22 12:15
Hi @fbdesignpro, i tried V 1.1 without success.

**Comment by fbdesignpro** [comment] 2021-02-05 19:15
Hi @fleschgordon! It's been a while, but I finally was able to reproduce and fix this issue! :) It will be fixed in 2.0.5, coming up very shortly.

It was caused by LaTeX escape sequences being present in feature names, causing mayhem at font render time.

Thanks again for the reports!

**Closed** 2021-02-05 19:16 UTC
Labels: bug
