### ISSUE TITLE
Graphs get cut off

### ISSUE THREAD

**Issue by Schwefelhexa** [fbdesignpro/sweetviz#143] opened 2023-05-08 13:17 UTC
The generated graphs get cut off, making the axes impossible to read.
See this image as an example:
<img width="236" alt="image" src="https://user-images.githubusercontent.com/40794797/236834086-5cb43eb9-65e4-45d1-b749-bf5ef4684b6d.png">

I'm willing to help on implementing a fix, but would need some pointers.

**Comment by fbdesignpro** [comment] 2023-08-20 12:22
@Schwefelhexa @NeverInAsh I know it's been a while, but can you confirm what environment you are seeing this (Python and/or browser)? I have not seen this. Thank you!

**Comment by fbdesignpro** [comment] 2023-11-14 12:31
Closing due to cannot reproduce and no further feedback

**Closed by fbdesignpro** 2023-11-14 12:31 UTC
Labels: can't repro issue

**Comment by heberthtorres** [comment] 2026-04-09 10:13
I have the same issue. I am currently using:
Python 3.11.5
sweetviz==2.3.2
Browsers: Chrome, Safari, Firefox
(BTW, Sweetviz is a great!!! Thanks)

**Comment by fbdesignpro** [comment] 2026-04-09 12:38
@heberthtorres thank you for the kind words! Actually if it's not confidential and you still have it can you email me the html report? fb@fbdesignpro.com, I'd like to see where in the construction it's differing from other reports that work.

**Comment by fbdesignpro** [comment] 2026-04-11 00:25
Fixed by #194
